configfile:
  - wa_profiles/wa/builds.yaml
  - wa_profiles/wa/input.yaml

cores: 8
keep-going: True
printshellcmds: True
reason: True
show-failed-logs: True
restart-times: 1
stats: stats.json
set-threads: tree=4
